#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'active_fedora'
require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

# RSpec::Core::RakeTask.new('spec')

# task :default => :spec